In [1]:
import torch
from torch import nn

In [3]:
x1 = torch.tensor([[11,21,31],[21,31,41]],dtype=torch.int)
x1.shape # torch.Size([2, 3])
# x2
x2 = torch.tensor([[12,22,32],[22,32,42]],dtype=torch.int)
x2.shape  # torch.Size([2, 3])
inputs = [x1, x2]

In [8]:
a = torch.cat(inputs, dim=0)

In [31]:
b = torch.stack([a,a])
b

tensor([[[11, 21, 31],
         [21, 31, 41],
         [12, 22, 32],
         [22, 32, 42]],

        [[11, 21, 31],
         [21, 31, 41],
         [12, 22, 32],
         [22, 32, 42]]], dtype=torch.int32)

In [32]:
c = torch.stack([b,b])
c

tensor([[[[11, 21, 31],
          [21, 31, 41],
          [12, 22, 32],
          [22, 32, 42]],

         [[11, 21, 31],
          [21, 31, 41],
          [12, 22, 32],
          [22, 32, 42]]],


        [[[11, 21, 31],
          [21, 31, 41],
          [12, 22, 32],
          [22, 32, 42]],

         [[11, 21, 31],
          [21, 31, 41],
          [12, 22, 32],
          [22, 32, 42]]]], dtype=torch.int32)

In [37]:
c[...,2]

tensor([[[31, 41, 32, 42],
         [31, 41, 32, 42]],

        [[31, 41, 32, 42],
         [31, 41, 32, 42]]], dtype=torch.int32)

In [36]:
c[...,2].unsqueeze(3)


tensor([[[[31],
          [41],
          [32],
          [42]],

         [[31],
          [41],
          [32],
          [42]]],


        [[[31],
          [41],
          [32],
          [42]],

         [[31],
          [41],
          [32],
          [42]]]], dtype=torch.int32)