In [4]:
from rich import print
from keras import layers
import tensorflow as tf
from rich import pretty
pretty.install()

In [5]:
x = tf.range(5)
x = tf.random.shuffle(x)
net = layers.Embedding(10,4)
net(x)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[-0.00709892,  0.03181444,  0.04227897, -0.03134799],
       [ 0.02759519,  0.04625995, -0.01390161, -0.01116551],
       [-0.00846473, -0.0080054 ,  0.04330726,  0.02819163],
       [-0.02792153,  0.0037209 ,  0.00191154, -0.0343999 ],
       [ 0.01524012,  0.01349466,  0.00248134, -0.03261046]],
      dtype=float32)>

In [7]:
net.trainable
net.trainable_variables
'''
[
    <tf.Variable 'embedding_1/embeddings:0' shape=(10, 4) dtype=float32, numpy=
array([[-0.00846473, -0.0080054 ,  0.04330726,  0.02819163],
       [ 0.02759519,  0.04625995, -0.01390161, -0.01116551],
       [-0.02792153,  0.0037209 ,  0.00191154, -0.0343999 ],
       [ 0.01524012,  0.01349466,  0.00248134, -0.03261046],
       [-0.00709892,  0.03181444,  0.04227897, -0.03134799],
       [ 0.01699238, -0.01580092,  0.04253182, -0.01670089],
       [ 0.00311543,  0.00607613,  0.02316804,  0.03303372],
       [ 0.03263738, -0.03469551,  0.0284413 ,  0.04712102],
       [-0.01462201, -0.00703601, -0.04295194,  0.04951351],
       [ 0.04463675, -0.02328815, -0.02553723, -0.02978516]],
      dtype=float32)>
]
'''

[
    <tf.Variable 'embedding_1/embeddings:0' shape=(10, 4) dtype=float32, numpy=
array([[-0.00846473, -0.0080054 ,  0.04330726,  0.02819163],
       [ 0.02759519,  0.04625995, -0.01390161, -0.01116551],
       [-0.02792153,  0.0037209 ,  0.00191154, -0.0343999 ],
       [ 0.01524012,  0.01349466,  0.00248134, -0.03261046],
       [-0.00709892,  0.03181444,  0.04227897, -0.03134799],
       [ 0.01699238, -0.01580092,  0.04253182, -0.01670089],
       [ 0.00311543,  0.00607613,  0.02316804,  0.03303372],
       [ 0.03263738, -0.03469551,  0.0284413 ,  0.04712102],
       [-0.01462201, -0.00703601, -0.04295194,  0.04951351],
       [ 0.04463675, -0.02328815, -0.02553723, -0.02978516]],
      dtype=float32)>
]