In [2]:
import numpy as np

![img](./img/Snipaste_2022-07-20_17-54-34.png)

In [6]:
# 状态转移矩阵
A = np.array([[0.5,0.2,0.3],[0.3,0.5,0.2],[0.2,0.3,0.5]])
# 输出概率矩阵 也就是发射矩阵
B = np.array([[0.5,0.5],[0.4,0.5]])
# 初始概率
pi = np.array([0.2,0.4,0.4])
#out 输出链，我们需要根据输出链推测出状态连
out = [0,1,0]
# xi是（序列长度，状态数量）形状的矩阵，每一行是一个时刻，每一列是每个状态输出的概率
# xi[0,0]即使t=0时刻，状态0输出结果的概率
xi = np.zeros((3,3))
# phi 里记录的是最有可能的路径
# phi[1,0] 是t=1时刻状态0的状态 最有可能总t=0到t=1的路径
phi = np.zeros((3,3))
A,B,pi,xi,phi

(array([[0.5, 0.2, 0.3],
        [0.3, 0.5, 0.2],
        [0.2, 0.3, 0.5]]),
 array([[0.5, 0.5],
        [0.4, 0.5]]),
 array([0.2, 0.4, 0.4]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]))