In [1]:
import tensorflow as tf
from tensorflow import keras

In [2]:
x = tf.random.normal([4,784])

net = tf.keras.layers.Dense(512)
#只需要指定输出的维度，输入时的维度会自动计算！！！

In [3]:
out = net(x)
out.shape#TensorShape([4, 512])

TensorShape([4, 512])

In [4]:
net.kernel.shape,net.bias.shape
#(TensorShape([784, 512]), TensorShape([512]))

(TensorShape([784, 512]), TensorShape([512]))

In [5]:
net = tf.keras.layers.Dense(10)
net.get_weights()#[]
net.build(input_shape=(None,4))
net.kernel.shape,net.bias.shape
#(TensorShape([4, 10]), TensorShape([10]))

(TensorShape([4, 10]), TensorShape([10]))

In [6]:
x = tf.random.normal([2,3])

model = keras.Sequential([
    keras.layers.Dense(2,activation='relu'),
    keras.layers.Dense(2,activation='relu'),
    keras.layers.Dense(2),
])
model.build(input_shape=[None,3])#创建参数
model.summary()#查看网络结构

#手动查看
for p in model.trainable_variables:
    print(p.name,p.shape)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 2)                 8         
                                                                 
 dense_3 (Dense)             (None, 2)                 6         
                                                                 
 dense_4 (Dense)             (None, 2)                 6         
                                                                 
Total params: 20
Trainable params: 20
Non-trainable params: 0
_________________________________________________________________
dense_2/kernel:0 (3, 2)
dense_2/bias:0 (2,)
dense_3/kernel:0 (2, 2)
dense_3/bias:0 (2,)
dense_4/kernel:0 (2, 2)
dense_4/bias:0 (2,)


In [7]:
y = tf.constant([1,2,3,0,2])
y = tf.one_hot(y,depth=4)
y = tf.cast(y,tf.float32)

out = tf.random.normal([5,4])

loss1 = tf.reduce_mean(tf.square(y-out))
loss2 = tf.square(tf.norm(y-out))/20
loss3 = tf.reduce_mean(tf.losses.MSE(y,out))
loss1,loss2,loss3
'''
(<tf.Tensor: shape=(), dtype=float32, numpy=1.6195879>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.6195879>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.6195879>)
'''

'\n(<tf.Tensor: shape=(), dtype=float32, numpy=1.6195879>,\n <tf.Tensor: shape=(), dtype=float32, numpy=1.6195879>,\n <tf.Tensor: shape=(), dtype=float32, numpy=1.6195879>)\n'

In [8]:
a = tf.fill([4],0.25)
a*tf.math.log(a)/tf.math.log(2.)
-tf.reduce_sum(a*tf.math.log(a)/tf.math.log(2.))#2.0

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [9]:
a = tf.constant([0.1,0.1,0.1,0.7])
a*tf.math.log(a)/tf.math.log(2.)
-tf.reduce_sum(a*tf.math.log(a)/tf.math.log(2.))#numpy=1.3567796

<tf.Tensor: shape=(), dtype=float32, numpy=1.3567796>

In [10]:
tf.losses.categorical_crossentropy([0,1,0,0],[0.25,0.25,0.25,0.25])
#<tf.Tensor: shape=(), dtype=float32, numpy=1.3862944>
tf.losses.categorical_crossentropy([0,1,0,0],[0.1,0.8,0.1,0.1])
#<tf.Tensor: shape=(), dtype=float32, numpy=0.3184537>\
#类的形式
tf.losses.BinaryCrossentropy()([1],[0.1])
#<tf.Tensor: shape=(), dtype=float32, numpy=2.3025842>

<tf.Tensor: shape=(), dtype=float32, numpy=2.3025842>

In [11]:
w = tf.constant(1.)
x = tf.constant(2.)
y = x*w
with tf.GradientTape() as tape:
    tape.watch([w])
    y2=x*w
grad1 = tape.gradient(y,[w])#[None]
grad1

with tf.GradientTape() as tape:
    tape.watch([w])
    y2=x*w
grad1 = tape.gradient(y2,[w])#[<tf.Tensor: shape=(), dtype=float32, numpy=2.0>]
grad1

[<tf.Tensor: shape=(), dtype=float32, numpy=2.0>]

In [12]:
# with tf.GradientTape() as t1:
#     with tf.GradientTape() as t2:
#         y = x*w+b
#     dy_dw,dy_db = t2.gradient(y,[w,b])
# d2y_fw2 = t1.gradient(dy_dw,w)

In [13]:
a = tf.linspace(-10,10,10)
with tf.GradientTape() as tape:
    #对于tf.constant类型的变量，也可以使用tape.watch加入自动求导记录里
    tape.watch(a)
    y = tf.sigmoid(a)
grads = tape.gradient(y,[a])
grads
'''
[<tf.Tensor: shape=(10,), dtype=float64, numpy=
 array([4.53958077e-05, 4.18591319e-04, 3.83620191e-03, 3.32587242e-02,
        1.86326443e-01, 1.86326443e-01, 3.32587242e-02, 3.83620191e-03,
        4.18591319e-04, 4.53958077e-05])>]
'''


'\n[<tf.Tensor: shape=(10,), dtype=float64, numpy=\n array([4.53958077e-05, 4.18591319e-04, 3.83620191e-03, 3.32587242e-02,\n        1.86326443e-01, 1.86326443e-01, 3.32587242e-02, 3.83620191e-03,\n        4.18591319e-04, 4.53958077e-05])>]\n'

In [14]:
x= tf.random.normal([2,4])
w=tf.random.normal([4,3])
b = tf.zeros([3])
y = tf.constant([2,0])

with tf.GradientTape() as tape:
    tape.watch([w,b])
    prob = tf.nn.softmax(x@w+b,axis=1)
    loss = tf.reduce_mean(tf.losses.MSE(tf.one_hot(y,depth=3),prob))
    
grads = tape.gradient(loss,[w,b])
grads[0]

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 0.03861355, -0.03457694, -0.00403661],
       [ 0.02824939, -0.02418399, -0.00406542],
       [ 0.03575942, -0.034534  , -0.00122541],
       [ 0.01089776, -0.01278827,  0.00189052]], dtype=float32)>

In [15]:
x= tf.random.normal([2,4])
w=tf.random.normal([4,3])
b = tf.zeros([3])
y = tf.constant([2,0])

with tf.GradientTape() as tape:
    tape.watch([w,b])
    logits = x@w+b
    loss =  tf.reduce_mean(tf.losses.categorical_crossentropy(tf.one_hot(y,depth=3),logits,from_logits=True))
    
grads = tape.gradient(loss,[w,b])
grads[0]

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-0.29003704,  0.24017723,  0.04985982],
       [-0.14264886, -0.41502684,  0.5576757 ],
       [ 0.00087503, -0.44100258,  0.44012755],
       [-0.13506618, -0.14862609,  0.28369227]], dtype=float32)>

In [16]:
x = tf.random.normal([1,3]) 
w = tf.ones([3,1])
b = tf.ones([1])
y = tf.constant([1])

with tf.GradientTape() as tape:
    tape.watch([w,b])
    prob = tf.sigmoid(x@w+b)
    loss = tf.reduce_mean(tf.losses.MSE(y,prob))
    
grads = tape.gradient(loss,[w,b])
grads[0]

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[-0.01534693],
       [ 0.02782919],
       [-0.03759802]], dtype=float32)>