In [1]:
import tensorflow as tf
with tf.device('/gpu:0'):
    a = tf.constant(1)
with tf.device('/cpu:0'):
    b = tf.constant([[1,2],[3,4]])
print(a.device,b.device)

/job:localhost/replica:0/task:0/device:GPU:0 /job:localhost/replica:0/task:0/device:CPU:0


In [2]:
aa = a.cpu()
aa.device

Instructions for updating:
Use tf.identity instead.


'/job:localhost/replica:0/task:0/device:CPU:0'

In [3]:
b.numpy()

array([[1, 2],
       [3, 4]])

In [4]:
tf.rank(b)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [5]:
a = tf.range(5)
b = tf.Variable(a)

In [6]:
import numpy as np
tf.convert_to_tensor(np.ones([2,3]))
tf.convert_to_tensor([[1],[2]])

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[1],
       [2]])>

In [7]:
tf.zeros([2,2])
a= tf.ones([3,3,3])

In [8]:
tf.fill([2,2],10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [10, 10]])>

In [9]:
tf.random.normal([2,2],mean=1,stddev=1)
tf.random.truncated_normal([2,2],mean=0,stddev=1)
tf.random.uniform([2,2],minval=0,maxval=1,dtype=tf.float32)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.5962428 , 0.00568044],
       [0.807513  , 0.4754629 ]], dtype=float32)>

In [10]:
idx = tf.range(10)
idx = tf.random.shuffle(idx)
idx#<tf.Tensor: shape=(10,), dtype=int32, numpy=array([8, 1, 4, 7, 0, 5, 9, 2, 6, 3])>

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([5, 7, 9, 0, 1, 4, 2, 8, 6, 3])>

In [11]:
a = tf.random.normal([10,784])
b = tf.random.uniform([10],maxval=10,dtype=tf.float32)
print(b)
a = tf.gather(a,idx)
b = tf.gather(b,idx)
print(b)

tf.Tensor(
[3.4621394  3.2921731  9.70645    8.70905    0.39913774 4.094657
 4.968848   0.8976126  4.5782495  4.4341493 ], shape=(10,), dtype=float32)
tf.Tensor(
[4.094657   0.8976126  4.4341493  3.4621394  3.2921731  0.39913774
 9.70645    4.5782495  4.968848   8.70905   ], shape=(10,), dtype=float32)


In [12]:
out = tf.random.uniform([4,10])
y = tf.range(4)
y = tf.one_hot(y,depth=10)
'''
<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>
'''
loss = tf.keras.losses.mse(y,out)
loss#<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.23495364, 0.447443  , 0.32503885, 0.35922748], dtype=float32)>
loss =tf.reduce_mean(loss)
loss#<tf.Tensor: shape=(), dtype=float32, numpy=0.37056983>

<tf.Tensor: shape=(), dtype=float32, numpy=0.3500474>

In [13]:
from tensorflow import keras
net = keras.layers.Dense(10)
net.build((4,8))
net.kernel
net.bias

<tf.Variable 'bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [14]:
a = tf.random.normal([4,28,28,3])

In [15]:
a[1].shape
a[1,2]#以照片为例，就是第一张照片的第三行

<tf.Tensor: shape=(28, 3), dtype=float32, numpy=
array([[-1.6875918 ,  0.05063365,  0.2564059 ],
       [-0.56160927,  0.6604438 ,  0.08134396],
       [-0.37321237, -0.13202846, -0.52994406],
       [-1.1358895 ,  0.07859261, -0.77521324],
       [ 0.10383467,  1.6039869 ,  0.53682446],
       [ 0.1875986 , -0.5455161 ,  1.1985315 ],
       [-0.5496858 ,  1.1398267 ,  0.09438527],
       [-0.776853  , -0.454276  ,  0.51260847],
       [ 0.05468887, -1.3531421 ,  0.16334368],
       [-0.96687406, -1.3847421 , -0.44268867],
       [-2.0707378 ,  1.7431014 , -0.38382512],
       [ 0.8563144 , -0.18127787, -0.23821129],
       [-2.0117812 ,  0.987298  ,  1.1264547 ],
       [ 1.009085  , -1.2942806 , -0.22935958],
       [-0.92225116,  0.93820554, -0.7556255 ],
       [ 0.83733606,  2.2761247 ,  0.7958274 ],
       [-0.6710107 ,  0.4121469 ,  0.6607196 ],
       [ 2.0934327 ,  1.2093854 , -0.43708298],
       [ 0.7688738 , -0.01194857, -1.357202  ],
       [ 0.45503557,  1.5618721 ,  0.62

In [16]:
data = tf.range(3000)
data = tf.reshape(data,[10,100,3])
#例子:data:[classes,students,subjects]
tf.gather(data,axis=1,indices=[9,16,30]).shape#TensorShape([10, 3, 3])


TensorShape([10, 3, 3])

In [17]:
tf.gather_nd(data,[0])#0班的所有人的所有成绩
tf.gather_nd(data,[0,1])#0班的1号学生的所有成绩
a = tf.gather_nd(data,[[0,0,0],[0,0,1]])#<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 1])>

In [18]:
tf.gather_nd(data,[[0,0],[0,1]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5]])>

In [19]:
data.shape

TensorShape([10, 100, 3])

In [20]:
a =tf.ones([2,3,4])
tf.boolean_mask(a,mask=[[True,False,False],[True,True,True]])#对应[2,3]

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [21]:
a = tf.random.normal([4,28,28,3])
tf.reshape(a,[4,784,3])
tf.reshape(a,[4,-1,3]).shape#-1标志该部分会自动计算，但是要保证非-1部分的状态

TensorShape([4, 784, 3])

In [22]:
a = tf.random.normal((4,3,2,1))
a.shape
tf.transpose(a).shape#[1,2,3,4]
tf.transpose(a,perm = [0,1,3,2]).shape#TensorShape([4, 3, 1, 2])

TensorShape([4, 3, 1, 2])

In [23]:
a = tf.random.normal([4,35,8])
tf.expand_dims(a,axis=0).shape#TensorShape([1, 4, 35, 8])在前方增加

TensorShape([1, 4, 35, 8])

In [24]:
tf.squeeze(tf.zeros([1,2,1,1,1,3])).shape#TensorShape([2, 3])

TensorShape([2, 3])

In [25]:
b = tf.broadcast_to(tf.random.normal([4,1,1,1]),[4,23,23,3])
b.shape#TensorShape([4, 23, 23, 3])

TensorShape([4, 23, 23, 3])

In [26]:
a = tf.ones([4,2,3])
b = tf.fill([4,3,5],2.)
(a@b).shape#TensorShape([4, 2, 5])
tf.matmul(a,b).shape#TensorShape([4, 2, 5])

TensorShape([4, 2, 5])

In [27]:
x = tf.ones([4,2])
w = tf.ones([2,1])
b = tf.constant(0.1)
out = x@w+b
'''
<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[2.1],
       [2.1],
       [2.1],
       [2.1]], dtype=float32)>
'''
out = tf.nn.relu(out)
out

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[2.1],
       [2.1],
       [2.1],
       [2.1]], dtype=float32)>

In [28]:
a = tf.ones([4,35,8])
b = tf.ones([2,35,8])
c = tf.concat([a,b],axis=0)
c.shape#TensorShape([6, 35, 8])

TensorShape([6, 35, 8])

In [35]:
a = tf.ones([4,35,8])
b = tf.ones([4,35,8])

c = tf.stack([a,b],axis=0)
c.shape#TensorShape([2, 4, 35, 8])
aa,bb = tf.unstack(c,axis=0)
aa.shape,bb.shape#(TensorShape([4, 35, 8]), TensorShape([4, 35, 8]))

(TensorShape([4, 35, 8]), TensorShape([4, 35, 8]))

In [38]:
a = tf.ones([10,4,35,10])
res = tf.split(a,axis=0,num_or_size_splits=2)
len(res)#2
res = tf.split(a,axis=0,num_or_size_splits=[2,3,5])
res[0].shape,res[1].shape,res[2].shape
'''
(TensorShape([2, 4, 35, 10]),
 TensorShape([3, 4, 35, 10]),
 TensorShape([5, 4, 35, 10]))
'''

(TensorShape([2, 4, 35, 10]),
 TensorShape([3, 4, 35, 10]),
 TensorShape([5, 4, 35, 10]))

In [39]:
a = tf.ones([2,2])
tf.norm(a)#<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [48]:
a =tf.range(10)
a = tf.reshape(a,[2,5])
tf.argmax(a)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 1, 1, 1, 1], dtype=int64)>

In [51]:
a = tf.constant([1,2,3,4,5])
b = tf.range(5)
tf.equal(a,b)

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([False, False, False, False, False])>

In [52]:
a = tf.constant([4,2,2,4,3])
tf.unique(a)
#Unique(y=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 2, 3])>, idx=<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 1, 0, 2])>)

Unique(y=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 2, 3])>, idx=<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 1, 0, 2])>)

In [55]:
a = tf.random.shuffle(tf.range(5))
tf.sort(a,direction='DESCENDING')#<tf.Tensor: shape=(5,), dtype=int32, numpy=array([4, 3, 2, 1, 0])>
#direction: The direction in which to sort the values ('ASCENDING' or'DESCENDING').
tf.argsort(a)#<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 2, 3, 1, 4])>

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([4, 3, 2, 1, 0])>

In [57]:
a = tf.constant([
    [4,6,8],
    [9,4,7],
    [4,5,1]
])
res = tf.math.top_k(a,2)
res.indices#返回索引
'''
<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 1],
       [0, 2],
       [1, 0]])>
'''
res.values#返回值
'''
<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[8, 6],
       [9, 7],
       [5, 4]])>
'''

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[8, 6],
       [9, 7],
       [5, 4]])>

In [59]:
a = tf.constant([
    [4,6,8],
    [9,4,7],
    [4,5,1]
])
tf.pad(a,[[0,0],[1,1]])
'''
<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[0, 4, 6, 8, 0],
       [0, 9, 4, 7, 0],
       [0, 4, 5, 1, 0]])>
'''

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[0, 4, 6, 8, 0],
       [0, 9, 4, 7, 0],
       [0, 4, 5, 1, 0]])>

In [60]:
a = tf.constant([
    [4,6,8],
    [9,4,7],
    [4,5,1]
])
tf.tile(a,[1,2])#[1,2]1表示第一个维度复制的次数，2表示第二个维度复制1次
'''
<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[4, 6, 8, 4, 6, 8],
       [9, 4, 7, 9, 4, 7],
       [4, 5, 1, 4, 5, 1]])>
'''

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[4, 6, 8, 4, 6, 8],
       [9, 4, 7, 9, 4, 7],
       [4, 5, 1, 4, 5, 1]])>

In [63]:
a = tf.range(10)
tf.maximum(a,2)#数据的下限 ，也就是说如果小于2则变为2
tf.minimum(a,8)#数据的上限
tf.clip_by_value(a,2,8)#直接限定上下限
#<tf.Tensor: shape=(10,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5, 6, 7, 8, 8])>

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5, 6, 7, 8, 8])>

In [67]:
a = tf.random.normal([2,2],mean=10)
tf.norm(a)#<tf.Tensor: shape=(), dtype=float32, numpy=20.50416>
aa =tf.clip_by_norm(a,15)
tf.norm(aa)#<tf.Tensor: shape=(), dtype=float32, numpy=15.000001>

<tf.Tensor: shape=(), dtype=float32, numpy=15.000001>

In [72]:
a = tf.random.normal([3,3])
mask = a >0
tf.boolean_mask(a,mask)#返回mask对应的数值
indices =  tf.where(mask)#返回mask中true的坐标

In [74]:
A = tf.ones([3,3])
B = tf.zeros([3,3])
tf.where(mask,A,B)#mask中ture的位置返回A的元素，False返回B
'''
<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 1., 0.],
       [0., 0., 0.],
       [1., 1., 1.]], dtype=float32)>
'''

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 1., 0.],
       [0., 0., 0.],
       [1., 1., 1.]], dtype=float32)>

In [77]:
shape = tf.constant([8])
shape

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([8])>

In [84]:
y = tf.linspace(-2.,2,5)
x = tf.linspace(-2.,2,5)

points_x, points_y=tf.meshgrid(x,y)
points_x.shape#TensorShape([5, 5])
points = tf.stack([points_x,points_y],axis=2)
points

<tf.Tensor: shape=(5, 5, 2), dtype=float32, numpy=
array([[[-2., -2.],
        [-1., -2.],
        [ 0., -2.],
        [ 1., -2.],
        [ 2., -2.]],

       [[-2., -1.],
        [-1., -1.],
        [ 0., -1.],
        [ 1., -1.],
        [ 2., -1.]],

       [[-2.,  0.],
        [-1.,  0.],
        [ 0.,  0.],
        [ 1.,  0.],
        [ 2.,  0.]],

       [[-2.,  1.],
        [-1.,  1.],
        [ 0.,  1.],
        [ 1.,  1.],
        [ 2.,  1.]],

       [[-2.,  2.],
        [-1.,  2.],
        [ 0.,  2.],
        [ 1.,  2.],
        [ 2.,  2.]]], dtype=float32)>